/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gianluca' at '7/6/15 8:39 PM' with Gradle 2.5-20150605053008+0000
 *
 * @author gianluca, @date 7/6/15 8:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
